In [27]:
#Create a numpy array on your own and perform the following operations:
# array creation & initialization
# Mathematical & arithmetic operations
# Indexing, Slicing, Filtering
 
 
import numpy as np
a= np.array([[1, 2, 3],
             [4, 5, 6],
             [7, 8, 9]])
 
b= np.array([[9, 8, 7],
             [6, 5, 4],
             [3, 2, 1]])
 
arr= np.zeros((3,3))
print(arr)
arr=np.ones((3,3))
print(arr)
arr=np.eye(3)
print(arr)
 
np.sum
np.subtract
np.add  
 
# Matrix Arithmetic Operations
 
print(a + b)
print(a - b)
print(a * b)
print((a / b).round())
 
 
# Mathematical Operation
 
print(np.sqrt(a).round(2))      
print(np.log(a))        
print(np.sin(a))        
print(np.mean(a))      
 
 
# Matrix Multiplication (Dot Product)
print(a@b)
 
# Transpose of A & B
print(a.T)
print(b.T)
 
# Indexing, Slicing, Filtering
print(a[0,2])
print(a[1,1])
 

print(b[0,1])
print(b[2,2])
 
 
print("Slicing the array ")
print(a[:2, :2])
print("\n")
print(a[1:, :1])
print("\n")
print(a[2:])
print("\n")
print(a[1:])
 
print("\n xf")
print("\n")
 
print("Filtering \n")
print(a[a>1])
print("\n")
print(a[a % 2 == 0])
 

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[10 10 10]
 [10 10 10]
 [10 10 10]]
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]
[[0. 0. 0.]
 [1. 1. 2.]
 [2. 4. 9.]]
[[1.   1.41 1.73]
 [2.   2.24 2.45]
 [2.65 2.83 3.  ]]
[[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]
 [1.94591015 2.07944154 2.19722458]]
[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]
 [ 0.6569866   0.98935825  0.41211849]]
5.0
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[9 6 3]
 [8 5 2]
 [7 4 1]]
3
5
8
1
Slicing the array 
[[1 2]
 [4 5]]


[[4]
 [7]]


[[7 8 9]]


[[4 5 6]
 [7 8 9]]

 xf


Filtering 

[2 3 4 5 6 7 8 9]


[2 4 6 8]
